// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CurtainWrapper: typeof import('./src/components/curtains/CurtainWrapper.vue')['default']
    DropZone: typeof import('./src/components/DropZone.vue')['default']
    EditorDisplay: typeof import('./src/components/editor/EditorDisplay.vue')['default']
    EditorLayout: typeof import('./src/components/editor/EditorLayout.vue')['default']
    EditorLevelSelect: typeof import('./src/components/editor/EditorLevelSelect.vue')['default']
    EditorOverview: typeof import('./src/components/editor/EditorOverview.vue')['default']
    EditorRobeSelect: typeof import('./src/components/editor/EditorRobeSelect.vue')['default']
    EditorScarfSelect: typeof import('./src/components/editor/EditorScarfSelect.vue')['default']
    EditorSymbolSelect: typeof import('./src/components/editor/EditorSymbolSelect.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarItem: typeof import('./src/components/NavBarItem.vue')['default']
    PlayerDisplay: typeof import('./src/components/parser/PlayerDisplay.vue')['default']
    PlayerDisplayHeading: typeof import('./src/components/parser/PlayerDisplayHeading.vue')['default']
    PlayerDisplayItem: typeof import('./src/components/parser/PlayerDisplayItem.vue')['default']
    RobeClothAnim: typeof import('./src/components/curtains/RobeClothAnim.vue')['default']
    StatsDisplay: typeof import('./src/components/stats/StatsDisplay.vue')['default']
    StatsGeneralDisplay: typeof import('./src/components/stats/sections/StatsGeneralDisplay.vue')['default']
    StatsHoverItem: typeof import('./src/components/stats/sectionItems/StatsHoverItem.vue')['default']
    StatsItemRow: typeof import('./src/components/stats/sectionItems/StatsItemRow.vue')['default']
    StatsJourneyDisplay: typeof import('./src/components/stats/sections/StatsJourneyDisplay.vue')['default']
    StatsMiscDisplay: typeof import('./src/components/stats/sections/StatsMiscDisplay.vue')['default']
    StatsMuralDisplay: typeof import('./src/components/stats/sections/StatsMuralDisplay.vue')['default']
    StatsSectionHeading: typeof import('./src/components/stats/sectionHelpers/StatsSectionHeading.vue')['default']
    StatsSectionItem: typeof import('./src/components/stats/sectionHelpers/StatsSectionItem.vue')['default']
    StatsSymbolDisplay: typeof import('./src/components/stats/sections/StatsSymbolDisplay.vue')['default']
    StatsValueItem: typeof import('./src/components/stats/sectionItems/StatsValueItem.vue')['default']
  }
}

export {}
