import sym0 from "./symbols/0.svg";
import sym1 from "./symbols/1.svg";
import sym2 from "./symbols/2.svg";
import sym3 from "./symbols/3.svg";
import sym4 from "./symbols/4.svg";
import sym5 from "./symbols/5.svg";
import sym6 from "./symbols/6.svg";
import sym7 from "./symbols/7.svg";
import sym8 from "./symbols/8.svg";
import sym9 from "./symbols/9.svg";
import sym10 from "./symbols/10.svg";
import sym11 from "./symbols/11.svg";
import sym12 from "./symbols/12.svg";
import sym13 from "./symbols/13.svg";
import sym14 from "./symbols/14.svg";
import sym15 from "./symbols/15.svg";
import sym16 from "./symbols/16.svg";
import sym17 from "./symbols/17.svg";
import sym18 from "./symbols/18.svg";
import sym19 from "./symbols/19.svg";
import sym20 from "./symbols/20.svg";

import arrow1L from "./arrows/arrow1L.svg";
import arrow2L from "./arrows/arrow2L.svg";
import arrow3L from "./arrows/arrow3L.svg";
import arrow4L from "./arrows/arrow4L.svg";
import arrow1R from "./arrows/arrow1R.svg";
import arrow2R from "./arrows/arrow2R.svg";
import arrow3R from "./arrows/arrow3R.svg";
import arrow4R from "./arrows/arrow4R.svg";

import red1 from "./robes/red1.png";
import red2 from "./robes/red2.png";
import red3 from "./robes/red3.png";
import red4 from "./robes/red4.png";
import white2 from "./robes/white2.png";
import white3 from "./robes/white3.png";
import white4 from "./robes/white4.png";

import level1 from "./levels/1.png";
import level2 from "./levels/2.png";
import level3 from "./levels/3.png";
import level4 from "./levels/4.png";
import level5 from "./levels/5.png";
import level6 from "./levels/6.png";
import level7 from "./levels/7.png";
import level8 from "./levels/8.png";
import level9 from "./levels/9.png";
import level10 from "./levels/10.png";
import level11 from "./levels/11.png";

export const sym = [sym0, sym1, sym2, sym3, sym4, sym5, sym6, sym7, sym8, sym9, sym10, sym11, sym12, sym13, sym14, sym15, sym16, sym17, sym18, sym19, sym20];
export const arrow = [[arrow1L, arrow2L, arrow3L, arrow4L], [arrow1R, arrow2R, arrow3R, arrow4R]];
export const robe = [[red1, red2, red3, red4], [white2, white3, white4]];
export const level = [level1, level2, level3, level4, level5, level6, level7, level8, level9, level10, level11];
